version: "3.7"

services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    container_name: caddy
    ports:
      - 80:80
      - 443:443
    environment:
      - CADDY_INGRESS_NETWORKS=caddy
    networks:
      - caddy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/caddy:/data
    restart: always

  n8n:
    image: docker.n8n.io/n8nio/n8n
    ports:
      - 5678:5678
    environment:
      - N8N_HOST=${SUBDOMAIN}.${DOMAIN_NAME}
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - NODE_ENV=production
      - WEBHOOK_URL=https://${SUBDOMAIN}.${DOMAIN_NAME}/
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
    volumes:
      - n8n_data:/home/node/.n8n
      - ${DATA_FOLDER}/local_files:/files
    networks:
      - caddy
    labels:
      caddy: ${SUBDOMAIN}.${DOMAIN_NAME}
      # To avoid being crawled by Malicious Web Crawlers,
      # - Make index page to be forbidden.
      # - Set CouchDB into subdirectory
      caddy.handle_path: /*
      caddy.handle_path.0_respond: "\"\" 403"
      caddy.handle_path.0_header.-Server: ""
      caddy.handle_path_1: /home/*
      caddy.handle_path_1.0_reverse_proxy: "{{upstreams 5678}}"
    restart: always

volumes:
  caddy_data:
    external: true
  n8n_data:
    external: true

networks:
  caddy:
    external: true